In [2]:
import pandas as pd 
import numpy as np 
import json

In [3]:
# Load the subscriptions data
df_subs = pd.read_csv('../data/raw_subscriptions.csv')

In [4]:
# Look at the first 10 rows
print("--- FIRST 10 ROWS ---")
df_subs.head(10)

--- FIRST 10 ROWS ---

    user_id signup_date   plan_type payment_method    status cancellation_date
0  USR_0001  2025-01-01  Individual  Google Wallet  Canceled        2025-06-16
1  USR_0002  2025-01-01     Student         PayPal  Canceled        2025-02-07
2  USR_0003  2025-01-01      Family  Google Wallet    Active               NaN
3  USR_0004  2025-01-02  Individual  Google Wallet  Canceled        2025-03-08
4  USR_0005  2025-01-02  Individual    Credit Card    Active               NaN
5  USR_0006  2025-01-03  Individual    Credit Card  Canceled        2025-02-04
6  USR_0007  2025-01-03  Individual  Google Wallet    Active               NaN
7  USR_0008  2025-01-03      Family    Credit Card  Canceled        2025-04-12
8  USR_0009  2025-01-04  Individual         PayPal  Canceled        2025-07-01
9  USR_0010  2025-01-04      Family         PayPal  Canceled        2025-03-02

In [5]:
# Look at information about data types
print("\n--- DATA INFO ---")
df_subs.info()

--- DATA INFO ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1000 non-null   object
 1   signup_date        1000 non-null   object
 2   plan_type          1000 non-null   object
 3   payment_method     1000 non-null   object
 4   status             1000 non-null   object
 5   cancellation_date  253 non-null    object
dtypes: object(6)
memory usage: 47.0+ KB

In [6]:
# Check what plan types we have
print(df_subs['plan_type'].unique())

['Individual' 'Student' 'Family' 'indivual_typo']

In [7]:
# Noticed that the plan type "individual_typo" looks like a typo. Let's check which rows have this value.
df_subs.query('plan_type == "indivual_typo"')

,user_id,signup_date,plan_type,payment_method,status,cancellation_date
49,USR_0050,2025-01-21,indivual_typo,PayPal,Active,NaN
83,USR_0084,2025-02-05,indivual_typo,Google Wallet,Active,NaN
275,USR_0276,2025-04-27,indivual_typo,Google Wallet,Active,NaN
357,USR_0358,2025-06-01,indivual_typo,Credit Card,Active,NaN
363,USR_0364,2025-06-04,indivual_typo,Google Wallet,Canceled,2025-10-24
484,USR_0485,2025-07-25,indivual_typo,Credit Card,Active,NaN
563,USR_0564,2025-08-27,indivual_typo,PayPal,Active,NaN
569,USR_0570,2025-08-30,indivual_typo,Credit Card,Canceled,2025-11-06
727,USR_0728,2025-11-05,indivual_typo,Credit Card,Active,NaN
762,USR_0763,2025-11-20,indivual_typo,Credit Card,Active,NaN
782,USR_0783,2025-11-28,indivual_typo,Google Wallet,Active,NaN
801,USR_0802,2025-12-06,indivual_typo,Google Wallet,Active,NaN
898,USR_0899,2026-01-17,indivual_typo,Google Wallet,Active,NaN
905,USR_0906,2026-01-20,indivual_typo,Credit Card,Canceled,2026-03-09
927,USR_0928,2026-01-29,indivual_typo,PayPal,Canceled,2026-06-27

In [8]:
# Fix the plan_type typos using a mapping dictionary
plan_mapping = {
    'Individual': 'Individual',
    'Family': 'Family',
    'Student': 'Student',
    'indivual_typo': 'Individual'
}
df_subs['plan_type'] = df_subs['plan_type'].map(plan_mapping)

In [9]:
# Noticed from the Data Type Info that the signup_date and cancellation_date columns are being read in as objects (strings) instead of datetime. Let's convert those.
df_subs['signup_date'] = pd.to_datetime(df_subs['signup_date'])
df_subs['cancellation_date'] = pd.to_datetime(df_subs['cancellation_date'])

In [10]:
# Let's verify that our transformations for plan_type worked
print(df_subs['plan_type'].unique())

['Individual' 'Student' 'Family']

In [11]:
# Let's verify that our traansformation for the date columns worked by looking at the data types again
df_subs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            1000 non-null   object
 1   signup_date        1000 non-null   datetime64[ns]
 2   plan_type          1000 non-null   object
 3   payment_method     1000 non-null   object
 4   status             1000 non-null   object
 5   cancellation_date  253 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(4)
memory usage: 47.0+ KB

In [14]:
# Load activity logs from JSON file
df_logs = pd.read_json('../data/raw_activity_logs.json')

In [16]:
# Read first 10 rows of activity logs
print("\n--- FIRST 10 ROWS ---")
df_logs.head(10)

--- FIRST 10 ROWS ---

,log_id,user_id,activity_date,device_type,minutes_streamed,ad_clicks_avoided
0,LOG_100001,USR_0001,2025-01-01,TV,159,3
1,LOG_100002,USR_0001,2025-01-05,Mobile,16,1
2,LOG_100003,USR_0001,2025-01-09,Mobile,55,1
3,LOG_100004,USR_0001,2025-01-13,TV,12,2
4,LOG_100005,USR_0001,2025-01-17,Mobile,34,3
5,LOG_100006,USR_0001,2025-01-21,Mobile,36,2
6,LOG_100007,USR_0002,2025-01-01,Desktop,31,4
7,LOG_100008,USR_0002,2025-01-05,Mobile,24,4
8,LOG_100009,USR_0002,2025-01-09,Mobile,42,2
9,LOG_100010,USR_0002,2025-01-13,Mobile,33,4

In [17]:
# Check Data types of activity logs
print("\n---DATA INFO---")
df_logs.info()

---DATA INFO---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18075 entries, 0 to 18074
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   log_id             18075 non-null  object
 1   user_id            18075 non-null  object
 2   activity_date      18075 non-null  object
 3   device_type        18075 non-null  object
 4   minutes_streamed   18075 non-null  int64
 5   ad_clicks_avoided  18075 non-null  int64
dtypes: int64(2), object(4)
memory usage: 847.4+ KB

In [18]:
# Check device types in activity logs
df_logs['device_type'].unique()

array(['TV', 'Mobile', 'Desktop'], dtype=object)

In [24]:
# Convert activity_date from string to datetime
df_logs['activity_date'] = pd.to_datetime(df_logs['activity_date'])

In [25]:
# Verify change by checking data types again
print("\n--- UPDATED DATA TYPES ---")
df_logs.info()

--- UPDATED DATA TYPES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18075 entries, 0 to 18074
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   log_id             18075 non-null  object
 1   user_id            18075 non-null  object
 2   activity_date      18075 non-null  datetime64[ns]
 3   device_type        18075 non-null  object
 4   minutes_streamed   18075 non-null  int64
 5   ad_clicks_avoided  18075 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 847.4+ KB

In [ ]:
# Check number of rows in activity logs df before merge
df_logs.shape

(18075, 6)

In [26]:
# Like a SQL join, we will merge the subscriptions and activity logs dataframes together using the user_id column
df_master = pd.merge(df_logs, df_subs, on='user_id', how='left')

In [27]:
# Let's look at the master dataframe to verify the merge
print('\n--- MASTER DATAFRAME ---')
df_master

--- MASTER DATAFRAME ---

,log_id,user_id,activity_date,device_type,minutes_streamed,ad_clicks_avoided,signup_date,plan_type,payment_method,status,cancellation_date
0,LOG_100001,USR_0001,2025-01-01,TV,159,3,2025-01-01,Individual,Google Wallet,Canceled,2025-06-16
1,LOG_100002,USR_0001,2025-01-05,Mobile,16,1,2025-01-01,Individual,Google Wallet,Canceled,2025-06-16
2,LOG_100003,USR_0001,2025-01-09,Mobile,55,1,2025-01-01,Individual,Google Wallet,Canceled,2025-06-16
3,LOG_100004,USR_0001,2025-01-13,TV,12,2,2025-01-01,Individual,Google Wallet,Canceled,2025-06-16
4,LOG_100005,USR_0001,2025-01-17,Mobile,34,3,2025-01-01,Individual,Google Wallet,Canceled,2025-06-16
...,...,...,...,...,...,...,...,...,...,...,...
18070,LOG_118071,USR_1000,2026-03-09,Mobile,16,1,2026-03-01,Individual,Google Wallet,Active,NaT
18071,LOG_118072,USR_1000,2026-03-13,Mobile,21,1,2026-03-01,Individual,Google Wallet,Active,NaT
18072,LOG_118073,USR_1000,2026-03-17,Mobile,49,2,2026-03-01,Individual,Google Wallet,Active,NaT
18073,LOG_118074,USR_1000,2026-03-21,Mobile,56,5,2026-03-01,Individual,Google Wallet,Active,NaT
18074,LOG_118075,USR_1000,2026-03-25,Desktop,7,2,2026-03-01,Individual,Google Wallet,Active,NaT

In [ ]:
# Check number of rows in master df after merge
df_master.shape

(18075, 11)

In [30]:
import os

In [32]:
# Create a directory for cleaned/processed data if it doesn't exist
os.makedirs('../data/processed', exist_ok=True)

In [34]:
# Save the master dataframe to a clean CSV file, and set index to False to avoid the extra default column
df_master.to_csv('../data/processed/clean_streaming_activity.csv', index=False)